'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';import {request} from '@/lib/api';import {Plus,RefreshCw,Check,ChevronDown,ChevronUp,BookOpen,AlertCircle,Target,Play,Star,Flame} from 'lucide-react';
export type ModuleKey='books'|'questions'|'attempts'|'review'|'teaching'|'exams'|'readiness'|'topics';
type Row=Record<string,any>;
const titles:Record<ModuleKey,string>={books:'کتاب‌های من',questions:'بانک تست',attempts:'ثبت و سابقه تلاش',review:'مرور هوشمند',teaching:'تدریس و هدف‌گذاری',exams:'مرکز آزمون',readiness:'آمادگی آزمون',topics:'درخت مباحث آموزشی'};
const desc:Record<ModuleKey,string>={books:'کتاب‌ها را بساز و ساختار فصل‌ها و بخش‌ها را متناسب با منبع خودت بچین.',questions:'شماره و پاسخ تست‌ها را ثبت کن؛ متن سؤال در سامانه ذخیره نمی‌شود.',attempts:'هر بار حل تست به‌صورت یک سابقه مستقل ثبت می‌شود.',review:'تست‌های نیازمند مرور را از روی سابقه و علامت‌های مهم و سخت بساز.',teaching:'وضعیت تدریس و تعداد تست هدف هر مبحث را دنبال کن.',exams:'آزمون تعریف کن، اجراهای مختلف را نگه دار و پاسخ‌ها را ثبت کن.',readiness:'مباحث آزمون آینده را انتخاب کن تا برآورد و فهرست تمرین بسازی.',topics:'مبحث‌های آموزشی مستقل از ساختار فصل‌های کتاب هستند.'};
const fields:Record<ModuleKey,{key:string,label:string,type?:string,source?:string,options?:[string,string][]}[]>={
 books:[{key:'title',label:'عنوان کتاب'},{key:'subject',label:'درس'},{key:'publisher',label:'ناشر'},{key:'grade',label:'پایه'},{key:'field',label:'رشته'}],
 questions:[{key:'book_id',label:'کتاب',type:'select',source:'books'},{key:'book_node_id',label:'فصل / بخش',type:'select',source:'nodes'},{key:'display_number',label:'شماره تست'},{key:'correct_answer',label:'پاسخ صحیح'},{key:'publisher_difficulty',label:'سختی ناشر (اختیاری)'},{key:'is_important',label:'مهم',type:'check'},{key:'is_hard',label:'سخت',type:'check'}],
 attempts:[{key:'question_id',label:'تست',type:'select',source:'questions'},{key:'user_answer',label:'پاسخ شما (خالی = نزده)'},{key:'spent_seconds',label:'زمان (ثانیه)',type:'number'}],
 review:[], teaching:[{key:'topic_id',label:'مبحث',type:'select',source:'topics'},{key:'taught_status',label:'وضعیت تدریس',type:'select',options:[['not_taught','تدریس نشده'],['taught','تدریس شده'],['reviewed','مرور شده']]},{key:'notes',label:'یادداشت'}],
 exams:[{key:'title',label:'عنوان آزمون'},{key:'exam_type',label:'نوع آزمون',type:'select',options:[['single_subject','تک‌درس'],['multi_subject','چنددرس'],['mock','آزمایشی'],['checkup','چکاپ']]},{key:'planned_date',label:'تاریخ برنامه‌ریزی‌شده',type:'date'}],
 readiness:[{key:'title',label:'عنوان آزمون آینده'},{key:'planned_date',label:'تاریخ آزمون',type:'date'},{key:'topic_ids',label:'مباحث آزمون',type:'multi',source:'topics'}],
 topics:[{key:'title',label:'عنوان مبحث'},{key:'subject',label:'درس'},{key:'parent_id',label:'مبحث والد (اختیاری)',type:'select',source:'topics'}]
};
const labels:Record<string,string>={correct:'درست',wrong:'غلط',unanswered:'نزده',manual:'ثبت دستی',review:'مرور',exam:'آزمون',import:'ورود قبلی',not_taught:'تدریس نشده',taught:'تدریس شده',reviewed:'مرور شده',pending:'در انتظار',done:'انجام‌شده'};
function nice(v:any){if(v===true)return 'بله';if(v===false)return 'خیر';if(v===null||v===undefined||v==='')return '—';if(typeof v==='object')return JSON.stringify(v);if(typeof v==='string'&&v.startsWith('[')){try{return (JSON.parse(v) as string[]).join('، ')}catch{}}return labels[v]||String(v)}
export default function Workspace({module}:{module:ModuleKey}){const [rows,setRows]=useState<Row[]>([]),[books,setBooks]=useState<Row[]>([]),[topics,setTopics]=useState<Row[]>([]),[questions,setQuestions]=useState<Row[]>([]),[goals,setGoals]=useState<Row[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[expanded,setExpanded]=useState(''),[formOpen,setFormOpen]=useState(false);
const reload=useCallback(async()=>{setBusy(true);setError('');try{if(module==='books')setRows(await request('/books'));else if(module==='questions')setRows((await request<any>('/questions?size=100')).items);else if(module==='attempts')setRows((await request<any>('/attempts?size=100')).items);else if(module==='review')setRows(await request('/review/items'));else if(module==='topics')setRows(await request('/topics'));else if(module==='teaching'){setRows(await request('/teaching/records'));setGoals(await request('/teaching/goals'));}else if(module==='exams')setRows(await request('/exams'));else setRows(await request('/readiness/plans'));}catch(e){setError(e instanceof Error?e.message:'دریافت اطلاعات ناموفق بود')}finally{setBusy(false)}},[module]);
useEffect(()=>{reload();request<Row[]>('/books').then(setBooks).catch(()=>{});request<Row[]>('/topics').then(setTopics).catch(()=>{});request<any>('/questions?size=200').then(x=>setQuestions(x.items||[])).catch(()=>{})},[reload]);
const nodeOptions=useMemo(()=>books.flatMap(b=>(b.nodes||[]).map((n:Row)=>({...n,book_title:b.title}))),[books]);
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');setMessage('');const f=new FormData(e.currentTarget);const d:Row={};for(const x of fields[module]){if(x.type==='check')d[x.key]=f.get(x.key)==='on';else if(x.type==='multi')d[x.key]=f.getAll(x.key);else if(f.has(x.key))d[x.key]=f.get(x.key)||null;}try{let out:any;if(module==='books')out=await request('/books',{method:'POST',body:JSON.stringify(d)});if(module==='topics')out=await request('/topics',{method:'POST',body:JSON.stringify(d)});if(module==='questions')out=await request('/questions',{method:'POST',body:JSON.stringify(d)});if(module==='attempts')out=await request('/attempts',{method:'POST',body:JSON.stringify(d)});if(module==='teaching'){const {topic_id,...rest}=d;out=await request(`/teaching/records/${topic_id}`,{method:'PUT',body:JSON.stringify(rest)});}if(module==='exams')out=await request('/exams',{method:'POST',body:JSON.stringify(d)});if(module==='readiness')out=await request('/readiness/plans',{method:'POST',body:JSON.stringify(d)});setMessage(module==='attempts'?`تلاش ثبت شد: ${nice(out.result)}`:'با موفقیت ذخیره شد.');(e.target as HTMLFormElement).reset();await reload();}catch(err){setError(err instanceof Error?err.message:'ذخیره اطلاعات ناموفق بود')}}
async function generate(){setBusy(true);setError('');try{await request('/review/generate',{method:'POST',body:JSON.stringify({wrong:true,unanswered:true,previous:true,important:true,hard:true})});setMessage('فهرست مرور بر اساس داده‌های فعلی ساخته شد.');await reload()}catch(e){setError(e instanceof Error?e.message:'ساخت مرور ناموفق بود')}finally{setBusy(false)}}
async function complete(id:string){try{await request(`/review/items/${id}`,{method:'PATCH',body:JSON.stringify({status:'done'})});await reload()}catch(e){setError(e instanceof Error?e.message:'ثبت انجام مرور ناموفق بود')}}
async function addNode(book:Row){const title=window.prompt('عنوان فصل یا بخش را بنویسید');if(!title)return;const nodes=book.nodes||[];const parentChoice=nodes.length?window.prompt(`شماره گره والد را وارد کنید (خالی برای فصل اصلی):\\n${nodes.map((n:Row,i:number)=>`${i+1}. ${n.title}`).join('\\n')}`):null;const index=parentChoice?Number(parentChoice)-1:-1;if(parentChoice&&(!Number.isInteger(index)||index<0||index>=nodes.length)){setError('شماره گره والد معتبر نیست.');return}const parent_id=index>=0?nodes[index].id:null;try{await request(`/books/${book.id}/nodes`,{method:'POST',body:JSON.stringify({title,node_type:parent_id?'section':'chapter',parent_id,order_index:nodes.length})});await reload();request<Row[]>('/books').then(setBooks)}catch(e){setError(e instanceof Error?e.message:'افزودن بخش ناموفق بود')}}
async function addGoal(){const topic=window.prompt('شناسه مبحث برای هدف را وارد کنید:\n'+topics.map(t=>`${t.title}: ${t.id}`).join('\n'));if(!topic)return;const target=Number(window.prompt('هدف تعداد تست؟','30'));if(!Number.isFinite(target))return;try{await request('/teaching/goals',{method:'POST',body:JSON.stringify({topic_id:topic,target_count:target})});setMessage('هدف جدید ذخیره شد.');await reload()}catch(e){setError(e instanceof Error?e.message:'ثبت هدف ناموفق بود')}}
async function examAction(row:Row){try{const detail=await request<any>(`/exams/${row.id}`);if(!detail.questions?.length){setError('برای اجرای آزمون ابتدا تست به آن اضافه کنید.');return}const a=await request<any>(`/exams/${row.id}/attempts`,{method:'POST'});for(const q of detail.questions){const answer=window.prompt(`پاسخ تست شماره ${q.order_index+1} (خالی برای نزده):`);await request(`/exam-attempts/${a.id}/answers`,{method:'POST',body:JSON.stringify({exam_question_id:q.id,user_answer:answer||null})})}await request(`/exam-attempts/${a.id}/finish`,{method:'PATCH',body:JSON.stringify({})});setMessage('اجرای آزمون و پاسخ‌ها با موفقیت ذخیره شد.');await reload()}catch(e){setError(e instanceof Error?e.message:'شروع آزمون ناموفق بود')}}
async function attachExamQuestion(row:Row){if(!questions.length){setError('ابتدا تست‌هایی در بانک تست بساز.');return}const listing=questions.map(q=>`${q.display_number} · ${books.find(b=>b.id===q.book_id)?.title||'کتاب'} — ${q.id}`).join('\\n');const id=window.prompt(`شناسه تست برای افزودن را وارد کنید:\\n${listing}`);if(!id)return;try{const detail=await request<any>(`/exams/${row.id}`);await request(`/exams/${row.id}/questions`,{method:'POST',body:JSON.stringify({question_id:id,order_index:detail.questions.length})});setMessage('تست به آزمون اضافه شد.')}catch(e){setError(e instanceof Error?e.message:'افزودن تست ناموفق بود')}}
async function importPrevious(){const id=window.prompt(`شناسه تست را وارد کنید:\\n${questions.map(q=>`${q.display_number}: ${q.id}`).join('\\n')}`);if(!id)return;const result=window.prompt('نتیجه را وارد کنید: correct یا wrong یا unanswered','correct');if(!result||!['correct','wrong','unanswered'].includes(result)){setError('نتیجه واردشده معتبر نیست.');return}const user_answer=window.prompt('پاسخ ثبت‌شده (اختیاری):');try{await request('/previous-solved',{method:'POST',body:JSON.stringify({question_id:id,user_answer:user_answer||null,result})});setMessage('سابقه قبلی در جدول جداگانه ثبت شد.')}catch(e){setError(e instanceof Error?e.message:'ورود سابقه ناموفق بود')}}
async function planDetail(row:Row){try{const x=await request<any>(`/readiness/plans/${row.id}`);window.alert(`برآورد آمادگی: ${x.readiness_estimate ?? 0}%\nتست‌های پیشنهادی: ${x.tasks?.length||0}\n\n${x.disclaimer}`)}catch(e){setError(e instanceof Error?e.message:'دریافت برآورد ناموفق بود')}}
async function uploadExamAsset(row:Row,file?:File){if(!file)return;const form=new FormData();form.append('file',file);try{await request(`/exams/${row.id}/assets`,{method:'POST',body:form});setMessage('پیوست آزمون بارگذاری شد.')}catch(e){setError(e instanceof Error?e.message:'بارگذاری فایل ناموفق بود')}}
async function examHistory(row:Row){try{const d=await request<any>(`/exams/${row.id}`);if(!d.attempts.length){window.alert('هنوز اجرایی برای این آزمون ثبت نشده است.');return}const lines=[];for(const a of d.attempts){const result=await request<any>(`/exam-attempts/${a.id}`);lines.push(`${new Date(a.started_at).toLocaleString('fa-IR')} — درست ${result.summary.correct}، غلط ${result.summary.wrong}، نزده ${result.summary.unanswered}`)}window.alert(lines.join('\n'))}catch(e){setError(e instanceof Error?e.message:'دریافت سابقه آزمون ناموفق بود')}}

function sourceOptions(source?:string){if(source==='books')return books;if(source==='topics')return topics;if(source==='nodes')return nodeOptions;if(source==='questions')return questions.map(q=>({...q,title:`${q.display_number} — ${books.find(b=>b.id===q.book_id)?.title||'کتاب'}`}));return []}
function renderField(f:{key:string,label:string,type?:string,source?:string,options?:[string,string][]}){if(f.type==='check')return <label key={f.key} className="flex items-center gap-2 rounded-xl border border-[#e4eae3] p-3 text-sm"><input type="checkbox" name={f.key} className="accent-forest"/>{f.label}</label>;if(f.type==='select'||f.type==='multi'){const opts=f.options||sourceOptions(f.source).map(o=>[o.id,o.title||o.display_number] as [string,string]);return <label key={f.key} className="block text-xs font-bold text-[#66736a]">{f.label}<select multiple={f.type==='multi'} name={f.key} required={f.key!=='parent_id'} className="field mt-1.5" defaultValue={f.type==='multi'?[]:undefined}><option value="">انتخاب کنید</option>{opts.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{f.type==='multi'&&<span className="mt-1 block font-normal">برای انتخاب چند مبحث، Ctrl یا Command را نگه دارید.</span>}</label>}return <label key={f.key} className="block text-xs font-bold text-[#66736a]">{f.label}<input name={f.key} type={f.type||'text'} required={!['publisher_difficulty'].includes(f.key)} className="field mt-1.5"/></label>}
return <section><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><div className="mb-2 text-xs font-bold text-forest">فضای مطالعه / {titles[module]}</div><h1 className="text-3xl font-black">{titles[module]}</h1><p className="mt-2 max-w-2xl text-sm leading-7 text-muted">{desc[module]}</p></div><div className="flex gap-2"><button onClick={()=>reload()} className="btn-secondary"><RefreshCw size={16}/> تازه‌سازی</button>{module!=='review'&&<button onClick={()=>setFormOpen(!formOpen)} className="btn"><Plus size={18}/> افزودن</button>}{module==='review'&&<button onClick={generate} className="btn"><RotateIcon/> ساخت فهرست مرور</button>}{module==='attempts'&&<button onClick={importPrevious} className="btn-secondary">ورود تست‌های قبلی</button>}</div></div>
{error&&<div className="mb-4 flex items-center gap-2 rounded-xl bg-red-50 p-3 text-sm text-red-700"><AlertCircle size={17}/>{error}</div>}{message&&<div className="mb-4 rounded-xl bg-mint p-3 text-sm font-semibold text-forest">{message}</div>}
{formOpen&&module!=='review'&&<form onSubmit={submit} className="card mb-6 p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-bold">{titles[module]} جدید</h2><button type="button" onClick={()=>setFormOpen(false)} className="text-sm text-muted">بستن</button></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{fields[module].map(renderField)}</div><button className="btn mt-5"><Check size={17}/> ذخیره</button></form>}
{module==='books'&&<div className="grid gap-4 md:grid-cols-2">{rows.map(b=><article key={b.id} className="card p-5"><div className="flex items-start justify-between"><div className="flex gap-3"><div className="rounded-xl bg-mint p-3 text-forest"><BookOpen/></div><div><h3 className="font-bold">{b.title}</h3><p className="mt-1 text-sm text-muted">{b.subject} {b.publisher?`· ${b.publisher}`:''}</p></div></div><button onClick={()=>setExpanded(expanded===b.id?'':b.id)} className="rounded-lg p-2 hover:bg-paper">{expanded===b.id?<ChevronUp/>:<ChevronDown/>}</button></div>{expanded===b.id&&<div className="mt-4 border-t border-[#edf0ec] pt-4"><div className="mb-3 flex items-center justify-between text-sm font-bold">ساختار کتاب <button onClick={()=>addNode(b)} className="text-forest">+ افزودن فصل</button></div>{(b.nodes||[]).length===0?<p className="text-sm text-muted">هنوز فصلی اضافه نشده است.</p>:<div className="space-y-2">{b.nodes.map((n:Row)=><div key={n.id} className="flex items-center justify-between rounded-lg bg-paper px-3 py-2 text-sm"><span>{n.title}</span><span className="text-xs text-muted">{n.node_type}</span></div>)}</div>}</div>}</article>)}{rows.length===0&&!busy&&<Empty text="هنوز کتابی اضافه نکرده‌ای."/>}</div>}
{module==='topics'&&<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{rows.map(t=><article className="card p-4" key={t.id}><p className="font-bold">{t.title}</p><p className="mt-1 text-xs text-muted">{t.subject} · {t.status==='active'?'فعال':'بایگانی'}</p>{t.parent_id&&<p className="mt-2 text-xs text-forest">زیرمجموعه یک مبحث</p>}</article>)}{rows.length===0&&!busy&&<Empty text="درخت مباحثت را با افزودن مبحث بساز."/>}</div>}
{module==='review'&&<div className="grid gap-3">{rows.map(r=><article key={r.id} className="card flex flex-wrap items-center justify-between gap-3 p-4"><div><div className="font-bold">تست {r.question_id?.slice(0,8)}…</div><p className="mt-1 text-xs text-muted">دلایل: {nice(r.reasons)} · اولویت {r.priority}</p></div>{r.status==='pending'?<button onClick={()=>complete(r.id)} className="btn-secondary"><Check size={16}/> انجام شد</button>:<span className="rounded-full bg-mint px-3 py-1 text-xs font-bold text-forest">انجام‌شده</span>}</article>)}{rows.length===0&&!busy&&<Empty text="فهرست مرور خالی است؛ برای ساخت آن روی دکمه بالا بزن."/>}</div>}
{module==='teaching'&&<><div className="mb-4 flex justify-end"><button onClick={addGoal} className="btn-secondary"><Target size={16}/> تعریف هدف تعداد تست</button></div><div className="grid gap-4 md:grid-cols-2">{topics.map(t=>{const rec=rows.find(r=>r.topic_id===t.id);const goal=goals.find(g=>g.topic_id===t.id);return <article className="card p-5" key={t.id}><div className="flex items-center justify-between"><div><h3 className="font-bold">{t.title}</h3><p className="mt-1 text-xs text-muted">{t.subject}</p></div><select aria-label="وضعیت تدریس" className="field !w-auto" value={rec?.taught_status||'not_taught'} onChange={async e=>{try{await request(`/teaching/records/${t.id}`,{method:'PUT',body:JSON.stringify({taught_status:e.target.value})});await reload()}catch(err){setError(err instanceof Error?err.message:'به‌روزرسانی ناموفق بود')}}}><option value="not_taught">تدریس نشده</option><option value="taught">تدریس شده</option><option value="reviewed">مرور شده</option></select></div>{goal&&<p className="mt-4 rounded-xl bg-paper p-3 text-sm">هدف: {goal.target_count} تست</p>}</article>})}{topics.length===0&&<Empty text="ابتدا در بخش مباحث، مبحث ایجاد کن."/>}</div></>}
{module==='exams'&&<div className="grid gap-4 md:grid-cols-2">{rows.map(r=><article className="card p-5" key={r.id}><h3 className="font-bold">{r.title}</h3><p className="mt-1 text-sm text-muted">{nice(r.exam_type)}{r.planned_date?` · ${new Date(r.planned_date).toLocaleDateString('fa-IR')}`:''}</p><div className="mt-4 flex flex-wrap gap-2"><button className="btn-secondary" onClick={()=>attachExamQuestion(r)}><Plus size={16}/> افزودن تست</button><button className="btn" onClick={()=>examAction(r)}><Play size={16}/> اجرا و ثبت پاسخ‌ها</button><button className="btn-secondary" onClick={()=>examHistory(r)}>سابقه اجرا</button><label className="btn-secondary cursor-pointer">پیوست PDF/تصویر<input className="hidden" type="file" accept=".pdf,image/*" onChange={e=>uploadExamAsset(r,e.target.files?.[0])}/></label></div></article>)}{rows.length===0&&!busy&&<Empty text="هنوز آزمونی ثبت نشده است."/>}</div>}
{module==='readiness'&&<><p className="mb-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm leading-6 text-amber-900">درصد آمادگی یک برآورد بر اساس داده‌های ثبت‌شده است و نتیجه آزمون را تضمین نمی‌کند.</p><div className="grid gap-4 md:grid-cols-2">{rows.map(r=><article className="card p-5" key={r.id}><div className="flex items-center justify-between"><div><h3 className="font-bold">{r.title}</h3><p className="mt-1 text-sm text-muted">تاریخ: {r.planned_date?new Date(r.planned_date).toLocaleDateString('fa-IR'):'تعیین نشده'}</p></div><div className="rounded-xl bg-mint px-3 py-2 text-center font-black text-forest">{r.readiness_estimate??'—'}<small className="block text-[10px]">درصد</small></div></div><button onClick={()=>planDetail(r)} className="btn-secondary mt-4"><Target size={16}/> مشاهده فهرست کار</button></article>)}{rows.length===0&&!busy&&<Empty text="برای آزمون آینده برنامه بساز."/>}</div></>}
{(module==='questions'||module==='attempts')&&<div className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-right text-sm"><thead className="bg-[#f6f8f5] text-xs text-muted"><tr>{(module==='questions'?['شماره','کتاب','پاسخ صحیح','نشانه‌ها','']:['تست','پاسخ شما','نتیجه','زمان','تاریخ']).map((x,i)=><th key={i} className="px-4 py-3">{x}</th>)}</tr></thead><tbody className="divide-y divide-[#edf0ec]">{rows.map(r=><tr key={r.id} className="hover:bg-[#fbfcfa]">{module==='questions'?<><td className="px-4 py-3 font-bold">{r.display_number}</td><td className="px-4 py-3">{books.find(b=>b.id===r.book_id)?.title||'—'}</td><td className="px-4 py-3">{r.correct_answer}</td><td className="px-4 py-3"><span className="flex gap-2">{r.is_important&&<Star size={16} className="text-amber-500"/>}{r.is_hard&&<Flame size={16} className="text-rose-500"/>}</span></td><td className="px-4 py-3"></td></>:<><td className="px-4 py-3 font-bold">{questions.find(q=>q.id===r.question_id)?.display_number||r.question_id?.slice(0,8)}</td><td className="px-4 py-3">{r.user_answer||'نزده'}</td><td className="px-4 py-3">{nice(r.result)}</td><td className="px-4 py-3">{r.spent_seconds?`${r.spent_seconds} ثانیه`:'—'}</td><td className="px-4 py-3">{r.attempted_at?new Date(r.attempted_at).toLocaleDateString('fa-IR'):'—'}</td></>}</tr>)}</tbody></table>{rows.length===0&&!busy&&<Empty text={module==='questions'?'بانک تست خالی است.':'هنوز تلاشی ثبت نشده است.'}/>}</div></div>}
{busy&&<p className="mt-4 text-center text-sm text-muted">در حال دریافت اطلاعات…</p>}</section>}
function Empty({text}:{text:string}){return <div className="card col-span-full grid min-h-40 place-items-center p-8 text-center text-sm text-muted">{text}</div>}
function RotateIcon(){return <RefreshCw size={17}/>}
