"""initial phase1 models

Revision ID: e1a6d397a982
Revises: 
Create Date: 2026-09-25 08:07:26.130322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1a6d397a982'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('books',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=80), nullable=False),
    sa.Column('publisher', sa.String(length=120), nullable=True),
    sa.Column('grade', sa.String(length=40), nullable=True),
    sa.Column('field', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_books_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_books'))
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_books_user_id'), ['user_id'], unique=False)

    op.create_table('book_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.CheckConstraint("node_type IN ('chapter', 'section', 'subsection', 'mixed_tests', 'checkup', 'comprehensive', 'other')", name=op.f('ck_book_nodes_node_type')),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_nodes_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['book_nodes.id'], name=op.f('fk_book_nodes_parent_id_book_nodes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book_nodes'))
    )
    with op.batch_alter_table('book_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_nodes_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_nodes_parent_id'), ['parent_id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('book_node_id', sa.String(length=36), nullable=False),
    sa.Column('display_number', sa.String(length=50), nullable=False),
    sa.Column('correct_answer', sa.String(length=50), nullable=False),
    sa.Column('publisher_difficulty', sa.String(length=40), nullable=True),
    sa.Column('is_important', sa.Boolean(), nullable=False),
    sa.Column('is_hard', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_questions_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['book_node_id'], ['book_nodes.id'], name=op.f('fk_questions_book_node_id_book_nodes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_book_node_id'), ['book_node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_display_number'), ['display_number'], unique=False)

    op.create_table('question_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('user_answer', sa.String(length=50), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('spent_seconds', sa.Integer(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.CheckConstraint("result IN ('correct', 'wrong', 'unanswered')", name=op.f('ck_question_attempts_result')),
    sa.CheckConstraint("source IN ('manual', 'review', 'exam', 'import')", name=op.f('ck_question_attempts_source')),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_question_attempts_question_id_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_attempts'))
    )
    with op.batch_alter_table('question_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_attempts_attempted_at'), ['attempted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_attempts_question_id'), ['question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_attempts_question_id'))
        batch_op.drop_index(batch_op.f('ix_question_attempts_attempted_at'))

    op.drop_table('question_attempts')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_display_number'))
        batch_op.drop_index(batch_op.f('ix_questions_book_node_id'))
        batch_op.drop_index(batch_op.f('ix_questions_book_id'))

    op.drop_table('questions')
    with op.batch_alter_table('book_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_nodes_parent_id'))
        batch_op.drop_index(batch_op.f('ix_book_nodes_book_id'))

    op.drop_table('book_nodes')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_books_user_id'))

    op.drop_table('books')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
